development:
  # The app_name is used as the backup filename prefix
  app_name: ria
  # You must create the s3_bucket specified below via an external tool like S3 Browser, etc
  s3_bucket: ria-spoonfeed-backup-dev
  aws_access_key_id: AKIAILTU3LUR6KLQ2ODQ
  aws_secret_access_key: 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
  static_paths: "public"
  

staging:
  app_name: ria
  s3_bucket: ria-spoonfeed-backup-staging
  aws_access_key_id: AKIAILTU3LUR6KLQ2ODQ
  aws_secret_access_key: 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

production:
  app_name: ria
  s3_bucket: ria-spoonfeed-backup-production
  aws_access_key_id: AKIAILTU3LUR6KLQ2ODQ
  aws_secret_access_key: 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
  static_paths: "public"  