development:
  # The app_name is used as the backup filename prefix
  app_name: ria
  # You must create the s3_bucket specified below via an external tool like S3 Browser, etc
  s3_bucket: ria-spoonfeed-backup-dev
  aws_access_key_id: AKIAJOUV45SFLBRGHRXA
  aws_secret_access_key: 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
  static_paths: "public"

staging:
  app_name: ria
  s3_bucket: ria-spoonfeed-backup-staging
  aws_access_key_id: AKIAJOUV45SFLBRGHRXA
  aws_secret_access_key: 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

production:
  app_name: ria
  s3_bucket: ria-spoonfeed-backup-production
  aws_access_key_id: AKIAJOUV45SFLBRGHRXA
  aws_secret_access_key: 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
  static_paths: "public"  