
octopus:
  environments:
      - development
      - production
      - staging
  development:
    webservice:
      username: root
      password: 
      adapter: mysql2
      database: ria_8oct
      socket: /opt/lampp/var/mysql/mysql.sock
  production:
    webservice:
      username: ria_staging
      password: 2x5qhe1lY2
      adapter: mysql2
      database: ria_cashew      
  staging:
    webservice:
      username: ria_staging
      password: 2x5qhe1lY2
      adapter: mysql2
      database: ria_cashew