
octopus:
  environments:
      - development
      - production
      - staging
  development:
    webservice:
      username: root
      password: 
      adapter: mysql2
      database: ria_16thaug
      socket: /opt/lampp/var/mysql/mysql.sock
  production: &development
    webservice:
      username: root
      password: 
      adapter: mysql2
      database: ria_16thaug
      socket: /opt/lampp/var/mysql/mysql.sock      
  staging:
    webservice:
      username: root
      password: 
      adapter: mysql2
      database: ria_staging
      socket: /opt/lampp/var/mysql/mysql.sock      


