development: &DEV
  token: heUg9OmCb9WITgaiKn5uw
  secret: trPK1YWlFyqt9aZf3dqSPJ5eQi3vuiYN56WBcDnMmSY
  callbackurl: http://parker.local:3000/twitter_authorization/

production: &PRODUCTION
  token: 2O3cZx2xW6mH3FqfNkXtw
  secret: yGfF87HbIZFDABqYs7EVgBQMupE93kVjOjITueUsRAs
  callbackurl: http://spoonfeed.restaurantintelligenceagency.com/twitter_authorization/

staging:
  <<: *PRODUCTION
  callbackurl: http://staging.restaurantintelligenceagency.com/twitter_authorization/

test:
  <<: *DEV

cucumber:
  <<: *DEV