
development: &DEV
  token: heUg9OmCb9WITgaiKn5uw
  secret: trPK1YWlFyqt9aZf3dqSPJ5eQi3vuiYN56WBcDnMmSY
  callbackurl: http://spoonfeed.hq.smack.st:3000/twitter_authorization/

production: &PRODUCTION
  token: 2O3cZx2xW6mH3FqfNkXtw
  secret: yGfF87HbIZFDABqYs7EVgBQMupE93kVjOjITueUsRAs
  callbackurl: http://spoonfeed.restaurantintelligenceagency.com/twitter_authorization/

staging:
  token: ZBklaKCBcrrNmEDsXeYjVg
  secret: aOybP6qNIVNBChEF06oI9c9brdOJIiLpyLVZ4ObQ
  callbackurl: http://staging.restaurantintelligenceagency.com/twitter_authorization/

test:
  <<: *DEV

cucumber:
  <<: *DEV